### ISSUE TITLE
Sticky toolbar

### ISSUE THREAD

**Issue by malvese** [musicbed/MirrorMark#6]
A sticky toolbar that stays at the top of the window could be practical when we edit long contents. Right now we have to scroll up to use the buttons for text far down.

It may also be a way to mitigate issue #5

**Comment by Pathsofdesign** [comment]
I think this particular request may be best implemented at the theme level (use a theme overwrite for your specific implementation). The current MirrorMark theme has height: auto on the editor so it expands with the content.

You could set .mirrormark-toolbar to position: fixed and set a z-index. With some CSS adjustments you can achieve what you're looking for.

Also, you could use key commands to achieve any of the actions in the toolbar. I'm going to close this one for now.

**Comment by malvese** [comment]
Makes sense. The markup is clean and flexible enough for this kind of customization to be easy with a few lines of css+js. Thank you!
